# SPDX-FileCopyrightText: 2025 Basingstoke Repair Network <dev@basingstoke.repair>
#
# SPDX-License-Identifier: MIT

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "Saturday"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(ci-deps)"
    reviewers:
      - "shymega"
    groups:
      gh-actions-deps:
        patterns:
          - "*"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "Saturday"
      time: "07:00"
      timezone: "Europe/London"
    commit-message:
      prefix: "chore(deps)"
    reviewers:
      - "shymega"
    groups:
      npm-deps:
        patterns:
          - "*"
