# SPDX-FileCopyrightText: 2025 Basingstoke Repair Network <dev@basingstoke.repair>
#
# SPDX-License-Identifier: MIT

name: Build site

on:
  push:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    name: Build the website

    steps:
      - uses: actions/checkout@v5
      - name: Install, build your site
        if: false
        run: |
          npm install --legacy-peer-deps
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          force_oprhan: true
